"""add customer address and province

Revision ID: 0002_add_address_and_province
Revises: 0001_initial_schema
Create Date: 2026-05-11 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_add_address_and_province'
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_address', sa.String(length=500), nullable=True))
    op.add_column('orders', sa.Column('customer_province', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'customer_province')
    op.drop_column('orders', 'customer_address')
    # ### end Alembic commands ###
